### ISSUE TITLE
Replace the social links on the home page

### ISSUE THREAD

**Issue by AhsanAyaz** [code-with-ahsan/cwa-web#29]
Instead of the existing home page links,
![image](https://user-images.githubusercontent.com/9844254/136674841-580447e4-97be-45a9-8329-13dc64d7ed04.png)

Add the following links
1. [Twitch](https://twitch.tv/CodeWithAhsan)
2. [Facebook](https://facebook.com/codewithahsan)
3. [GitHub](https://github.com/code-with-ahsan)

**Comment by Hasham-dev** [comment]
Hello @AhsanAyaz , I'm currently working on it.
Could you please assign it to me?
